#include "SfzTranspiler.h"
#include "export/BundleExporter.h"
#include "../core/INodeVisitor.h"
#include "../core/IUiVisitor.h"

QString SfzTranspiler::generate(const ProjectManager* pm, bool isBundle, const QString& sampleDirPrefix, const QString& bgName) {
    QString output;
    output += "// Generated by SamplerEditor\n\n";
    output += "<control>\n";
    
    int ccCounter = 70;
    QMap<QUuid, QMap<QString, int>> nodePropertyToCC;
    
    class SfzUiVisitor : public IUiVisitor {
        QString& output;
        int& ccCounter;
        QMap<QUuid, QMap<QString, int>>& nodePropertyToCC;
    public:
        SfzUiVisitor(QString& out, int& cc, QMap<QUuid, QMap<QString, int>>& npMap) 
            : output(out), ccCounter(cc), nodePropertyToCC(npMap) {}
        void visit(const UiKnob* k) override {
            QString name = k->name.isEmpty() ? "Knob" : k->name;
            output += QString("label_cc%1=%2\n").arg(ccCounter).arg(name);
            output += QString("set_cc%1=0\n").arg(ccCounter);
            if (!k->targetNodeId.isNull() && !k->targetProperty.isEmpty()) {
                nodePropertyToCC[k->targetNodeId][k->targetProperty] = ccCounter;
            }
            ccCounter++;
        }
        void visit(const UiSlider*) override {}
        void visit(const UiButton*) override {}
        void visit(const UiLabel*) override {}
        void visit(const UiShape*) override {}
        void visit(const UiImage*) override {}
        void visit(const UiMenu*) override {}
        void visit(const UiXYPad*) override {}
        void visit(const UiOscilloscope*) override {}
        void visit(const UiKeyboard*) override {}
        void visit(const UiTab*) override {}
        void visit(const UiLine*) override {}
        void visit(const UiMultiFrameImage*) override {}
    };
    
    SfzUiVisitor uiVisitor(output, ccCounter, nodePropertyToCC);
    for (const auto& pair : pm->getAllUiComponents()) {
        pair.second->accept(&uiVisitor);
    }
    output += "\n";
    
    class SfzGroupsVisitor : public INodeVisitor {
        QString& output;
        const ProjectManager* pm;
        const QMap<QUuid, QMap<QString, int>>& nodePropertyToCC;
        const QString& sampleDirPrefix;
    public:
        SfzGroupsVisitor(QString& out, const ProjectManager* p, const QMap<QUuid, QMap<QString, int>>& npMap, const QString& sdp)
            : output(out), pm(p), nodePropertyToCC(npMap), sampleDirPrefix(sdp) {}
            
        void visit(const SampleGroup* sg) override {
            output += "<group>\n";
            output += QString("ampeg_attack=%1\n").arg(sg->ampEnv.attack);
            output += QString("ampeg_decay=%1\n").arg(sg->ampEnv.decay);
            output += QString("ampeg_sustain=%1\n").arg(sg->ampEnv.sustain * 100.0);
            output += QString("ampeg_release=%1\n").arg(sg->ampEnv.release);
            output += QString("volume=%1\n").arg(sg->volume);
            output += QString("pan=%1\n").arg(sg->pan);
            
            if (nodePropertyToCC.contains(sg->id) && nodePropertyToCC[sg->id].contains("volume")) {
                output += QString("gain_oncc%1=12\n").arg(nodePropertyToCC[sg->id]["volume"]);
            }
            
            auto conns = pm->getConnectionsForNode(sg->id);
            for (const auto& c : conns) {
                if (c.sourceId == sg->id) {
                    Node* target = pm->getNode(c.targetId);
                    if (target && target->type == "Filter") {
                        FilterNode* fn = static_cast<FilterNode*>(target);
                        output += QString("fil_type=%1\n").arg(fn->filterType);
                        output += QString("cutoff=%1\n").arg(fn->cutoff);
                        output += QString("resonance=%1\n").arg(fn->resonance);
                        if (nodePropertyToCC.contains(fn->id) && nodePropertyToCC[fn->id].contains("cutoff")) {
                            output += QString("cutoff_oncc%1=9600\n").arg(nodePropertyToCC[fn->id]["cutoff"]);
                        }
                    }
                }
            }
            output += "\n";
            
            for (const Zone& z : sg->zones) {
                output += "<region>\n";
                QString exportPath = z.samplePath;
                if (!sampleDirPrefix.isEmpty()) {
                    exportPath = sampleDirPrefix + BundleExporter::getSafeExportName(z.samplePath, false);
                }
                output += QString("sample=%1\n").arg(exportPath);
                output += QString("lokey=%1 hikey=%2\n").arg(z.loNote).arg(z.hiNote);
                output += QString("pitch_keycenter=%1\n").arg(z.rootNote);
                output += QString("lovel=%1 hivel=%2\n").arg(z.loVel).arg(z.hiVel);
                if (z.seqPosition > 1) output += QString("seq_position=%1\n").arg(z.seqPosition);
                if (z.keySwitchNote != -1) output += QString("sw_last=%1\n").arg(z.keySwitchNote);
                output += "\n";
            }
        }
        void visit(const BusNode*) override {}
        void visit(const DelayNode*) override {}
        void visit(const ReverbNode*) override {}
        void visit(const FilterNode*) override {}
        void visit(const ChorusNode*) override {}
        void visit(const GainNode*) override {}
        void visit(const PhaserNode*) override {}
        void visit(const PitchShifterNode*) override {}
        void visit(const WaveFolderNode*) override {}
        void visit(const WaveShaperNode*) override {}
        void visit(const StereoSimulatorNode*) override {}
        void visit(const BitCrusherNode*) override {}
        void visit(const EqualizerNode*) override {}
    };
    
    SfzGroupsVisitor groupsVisitor(output, pm, nodePropertyToCC, sampleDirPrefix);
    for (const auto& pair : pm->getAllNodes()) {
        pair.second->accept(&groupsVisitor);
    }
    
    output += "\n// Effects Section\n";
    
    class SfzEffectsVisitor : public INodeVisitor {
        QString& output;
        const ProjectManager* pm;
        const QMap<QUuid, QMap<QString, int>>& nodePropertyToCC;
    public:
        SfzEffectsVisitor(QString& out, const ProjectManager* p, const QMap<QUuid, QMap<QString, int>>& npMap)
            : output(out), pm(p), nodePropertyToCC(npMap) {}
            
        void visit(const SampleGroup*) override {}
        void visit(const BusNode*) override {}
        
        bool isGlobalEffect(const Node* node) {
            for (const auto& c : pm->getConnectionsForNode(node->id)) {
                if (c.targetId == node->id) {
                    Node* src = pm->getNode(c.sourceId);
                    if (src && src->type == "SampleGroup") return false;
                }
            }
            return true;
        }
        
        void visit(const DelayNode* d) override {
            if (d->bypassed) return;
            if (isGlobalEffect(d)) {
                output += "<effect>\n";
                output += "type=delay\n";
                output += QString("delay_time=%1\n").arg(d->time);
                output += QString("delay_feedback=%1\n").arg(d->feedback * 100.0);
                output += "\n";
            }
        }
        
        void visit(const ReverbNode* r) override {
            if (r->bypassed) return;
            if (isGlobalEffect(r)) {
                output += "<effect>\n";
                output += "type=reverb\n";
                output += QString("room_size=%1\n").arg(r->size);
                output += QString("damping=%1\n").arg(r->damp);
                if (nodePropertyToCC.contains(r->id) && nodePropertyToCC[r->id].contains("size")) {
                    output += QString("room_size_oncc%1=100\n").arg(nodePropertyToCC[r->id]["size"]);
                }
                output += "\n";
            }
        }
        
        void visit(const FilterNode* f) override {
            if (f->bypassed) return;
            if (isGlobalEffect(f)) {
                output += "<effect>\n";
                output += QString("fil_type=%1\n").arg(f->filterType);
                output += QString("cutoff=%1\n").arg(f->cutoff);
                output += QString("resonance=%1\n").arg(f->resonance);
                output += "\n";
            }
        }
        
        void visit(const ChorusNode*) override {}
        void visit(const GainNode*) override {}
        void visit(const PhaserNode*) override {}
        void visit(const PitchShifterNode*) override {}
        void visit(const WaveFolderNode*) override {}
        void visit(const WaveShaperNode*) override {}
        void visit(const StereoSimulatorNode*) override {}
        void visit(const BitCrusherNode*) override {}
        void visit(const EqualizerNode*) override {}
    };
    
    SfzEffectsVisitor effectsVisitor(output, pm, nodePropertyToCC);
    for (const auto& pair : pm->getAllNodes()) {
        pair.second->accept(&effectsVisitor);
    }
    
    return output;
}
